-- Clean database

DROP TABLE CLICK IF EXISTS;
DROP TABLE LINK IF EXISTS;

-- Link

CREATE TABLE LINK(
  CUSTOMURL VARCHAR(50) PRIMARY KEY, -- Custom URL
  ORIGINALURL VARCHAR(1024),
  CREATEQR BOOLEAN,
  CHECKSAFE BOOLEAN,
  ISSAFE BOOLEAN
)

-- CLICK

CREATE TABLE CLICK(
  ID  BIGINT IDENTITY,
  CUSTOMURL VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES LINK(CUSTOMURL),
  BROWSER		VARCHAR(50),				-- Browser
	PLATFORM	VARCHAR(50),				-- Platform
	IP			VARCHAR(20),				  -- IP
	COUNTRY		VARCHAR(50),					-- Country
	CITY        VARCHAR(50),                --City
	TIME TIMESTAMP
)